//input 5 employee data using constructor
#include<iostream.h>
#include<conio.h>
#include<string.h>
class emp
{
     private:
     int id;
     char ename[20];
     char department[20];
     float salary;
     public:
     emp(int,char e[20],char d[20],int s);
       {
	  id=i;
	  ename=e;
	  department=d;
	  salary=salary;
       }
     void main()
     {
	 cout<<"-------employee-------";
	 cout<<"take an employee id:"<<id<<end;
	 cout<<"take an employee name:"<<ename<<end;
	 cout<<"take an employee department:"<<dept<<end;
	 cout<<"take an employee salary:"<<salary<<end;
     }
     //get method to employee
     const char*getname()
     {
	  return name;
     }
};
     int main()
     //using array to get 5 employee object
     {
	  clrscr();
	  emp emp[5]
	  {
		employee(1,"sonal",it,20000);
		employee(2,"angali",ca,30000);
		employee(3,"prini",it,90000);
		employee(4,"reema",hr,50000);
		employee(5,"om",it,20000);
	  };
	  int j;
	  cout<<"take an employee records:";
	  for(j=0;j<5;j++)
	  {
	      if(salary(emp loyee[i].getname(),searname)==0)
	      {
		  cout<<"\n employee:"<<j+1<<":"<<end1;
		  employee[i],display();
		  found="true";
		  break;
	      }
	  }
	  if (!found)
	  {
	     cout<<"\n employee not found:"<<end1;

	  }
	  getch();
	  return 0;

